kind: Service
apiVersion: v1
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
  - name: https
    port: 443